### ISSUE TITLE
Composer autoloader not functioning for some users

### ISSUE THREAD

**Issue by slaFFik** [awesomemotive/wp-mail-smtp#110]
## Plugin version 

1.x

## Current Behavior

> https://wordpress.org/support/topic/http-error-500-when-trying-to-send-test/

```
[proxy_fcgi:error] [pid 29162:tid 140562451552000] [client 172.56.7.48:56888] AH01071: Got error ‘PHP message: PHP Fatal error: Uncaught Error: Call to undefined method Composer\\Autoload\\ClassLoader::setClassMapAuthoritative() in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wp-mail-smtp/vendor/composer/autoload_real.php:38\nStack trace:\n#0 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wp-mail-smtp/vendor/autoload.php(7): ComposerAutoloaderInitbd625bfb904527ebcdc364a59295e538::getLoader()\n#1 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wp-mail-smtp/src/Providers/Gmail/Mailer.php(53): require(‘/opt/bitnami/ap…’)\n#2 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wp-mail-smtp/src/Providers/Loader.php(170): WPMailSMTP\\Providers\\Gmail\\Mailer->__construct(Object(WPMailSMTP\\MailCatcher))\n#3 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wp-mail-smtp/src/Providers/Loader.php(127): WPMailSMTP\\Providers\\Loader->get_entity(‘gmail’, ‘Mailer’)\n#4 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wp-mail-smtp/src/MailCatcher.php(51): WPMailSMTP\\Providers\\Loader->get_mail…\n’,
```

## Expected Behavior

Composer autoloader should work as expected.

## Possible Solution

Composer at the top level of the site? No ideas right now.

**Comment by slaFFik** [comment]
I think the issue is not about composer, but about autoloading. I think, I've fixed that in https://github.com/awesomemotive/wp-mail-smtp/commit/1a2e994083a57da07771f1a72ed6a000b2f40ce8
