### ISSUE TITLE
Fatal Error -> undefined function

### ISSUE THREAD

**Issue by blueshiftwebservices** [awesomemotive/WP-Mail-SMTP#133]
## Expected Behavior

Email send with success notification.

## Current Behavior

No emails sending, fatal error thrown. 

[15-Apr-2024 17:30:02 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method WPMailSMTP\Core::get_utm_url() in /home1/bswsclients/prenticelaw.com/wp-content/plugins/wp-mail-smtp/src/Providers/SMTP/Options.php:42
Stack trace:
#0 wp-content/plugins/wp-mail-smtp/src/Providers/Loader.php(193): WPMailSMTP\Providers\SMTP\Options->__construct(NULL)
#1 wp-content/plugins/wp-mail-smtp/src/Providers/Loader.php(98): WPMailSMTP\Providers\Loader->get_entity('smtp', 'Options', Array)
#2 wp-content/plugins/wp-mail-smtp/src/MailCatcherV6.php(93): WPMailSMTP\Providers\Loader->get_options('smtp')
#3 wp-includes/pluggable.php(500): WPMailSMTP\MailCatcherV6->send()
#4 wp-content/plugins/contact-form-7/includes/mail.php(194): wp_mail(Array, 'Contact Form Su...', 'Contact Info:\nN...', Array, Array)
#5 wp-content/plugins/contact-form-7/includes/mail.php(19): W in wp-content/plugins/wp-mail-smtp/src/Providers/SMTP/Options.php on line 42

**Comment by capuderg** [comment]
Hi @blueshiftwebservices,

which version of the plugin are you using? This looks like a bad plugin update, missing plugin files or your host blocking some of the plugin files. Could you please download a fresh copy from https://wordpress.org/plugins/wp-mail-smtp/ and try to reinstall it on your site?

Let us know if this resolves it for you.
