### ISSUE TITLE
Cron tasks are not being processed

### ISSUE THREAD

**Issue by pabloleone** [awesomemotive/WP-Mail-SMTP#94]
## Expected Behavior
The cron job to process the queue.

## Current Behavior
The cron job keeps failing.

## Possible Solution
I'm not sure, the issue is with PHP 8 as far as I understand, but the code seems a little spaghetti to figure it out quickly.

## Steps to Reproduce
Have a multisite instance of WP with the plugin enabled and served with PHP8 and you'll see the error in the nginx logs.

## Screenshots
```
2021/07/20 16:40:41 [error] 13108#13108: *652109 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Unknown named parameter $tasks_meta_id in ***/wp-includes/class-wp-hook.php:292
Stack trace:
#0 ***/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()
#1 ***/wp-includes/plugin.php(551): WP_Hook->do_action()
#2 ***/wp-content/plugins/wp-mail-smtp-pro/vendor/woocommerce/action-scheduler/classes/actions/ActionScheduler_Action.php(22): do_action_ref_array()
#3 ***/wp-content/plugins/wp-mail-smtp-pro/vendor/woocommerce/action-scheduler/classes/abstracts/ActionScheduler_Abstract_QueueRunner.php(65): ActionScheduler_Action->execute()
#4 ***/wp-content/plugins/wp-mail-smtp-pro/vendor/woocommerce/action-scheduler/classes/ActionScheduler_QueueRunner.php(162): ActionScheduler_Abstract_QueueRunner->process_action()
#5 ***/wp-content/plugins/wp-mail-smtp-pro/vendor/woocommerce/action-scheduler/classes/ActionScheduler_QueueRunner.php(132): ActionScheduler_Qu" while reading response header from upstream,
```

**Comment by capuderg** [comment]
Hi @pabloleone,

which version of our pro plugin are you using?

Updating to our latest version might resolve this issue for you, if the recurring Action Scheduler task ("cron task") that is causing these issues is coming from our plugin.

Also, in the latest version, we are displaying the Action Scheduler table in WP Mail SMTP -> Tools -> Scheduled Actions. Please take a look and let me know which of the actions (their hook name) are causing these fatal errors.

Take care!

**Comment by capuderg** [comment]
Hi @pabloleone,

I'm closing this issue because of inactivity, but if you have any new information about this issue, please let us know and we'll reopen it.

Take care!
